"""empty message

Revision ID: 9de9a084546b
Revises: 3892ee57c67f
Create Date: 2021-04-28 02:21:34.944454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9de9a084546b'
down_revision = '3892ee57c67f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('category', sa.String(), nullable=True))
    op.add_column('product', sa.Column('details', sa.String(), nullable=True))
    op.drop_column('product', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('description', sa.VARCHAR(), nullable=True))
    op.drop_column('product', 'details')
    op.drop_column('product', 'category')
    # ### end Alembic commands ###
